# Generated by Django 3.1.2 on 2020-11-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_auto_20201021_1429'),
        ('memo', '0003_auto_20201021_1455'),
    ]

    operations = [
    ]
